import 'package:flutter/material.dart';
import '../../../../core/themes/app_theme.dart';
import '../../../../models/ai_summary.dart';
class AISummarySection extends StatelessWidget {
  final AISummary aiSummary;

  const AISummarySection({super.key, required this.aiSummary});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      color: Colors.white,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: AppTheme.secondaryBlue.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(
                  Icons.psychology_outlined,
                  color: AppTheme.secondaryBlue,
                  size: 20,
                ),
              ),
              const SizedBox(width: 12),
              const Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'AI Analysis',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                        color: AppTheme.textDark,
                      ),
                    ),
                    Text(
                      'Generated by AI for better understanding',
                      style: TextStyle(
                        fontSize: 11,
                        color: AppTheme.textLight,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          
          const SizedBox(height: 20),
          
          // AI Summary text
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.blue.shade50,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Text(
              aiSummary.summary,
              style: TextStyle(
                fontSize: 14,
                color: AppTheme.textDark,
                height: 1.6,
              ),
            ),
          ),
          
          const SizedBox(height: 24),
          
          // Pros section
          _buildSection(
            'Pros',
            aiSummary.pros,
            AppTheme.successGreen,
            Icons.check_circle_outline,
          ),
          
          const SizedBox(height: 20),
          
          // Cons section
          _buildSection(
            'Cons',
            aiSummary.cons,
            Colors.orange.shade600,
            Icons.warning_amber_outlined,
          ),
          
          const SizedBox(height: 20),
          
          // Risks section
          _buildSection(
            'Risks',
            aiSummary.risks,
            Colors.red.shade600,
            Icons.error_outline,
          ),
        ],
      ),
    );
  }
  
  Widget _buildSection(String title, List<String> items, Color color, IconData icon) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(icon, color: color, size: 20),
            const SizedBox(width: 8),
            Text(
              title,
              style: TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.w600,
                color: color,
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        ...items.map((item) => Padding(
          padding: const EdgeInsets.only(bottom: 8),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                margin: const EdgeInsets.only(top: 6),
                width: 6,
                height: 6,
                decoration: BoxDecoration(
                  color: color,
                  shape: BoxShape.circle,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  item,
                  style: TextStyle(
                    fontSize: 13,
                    color: AppTheme.textDark,
                    height: 1.5,
                  ),
                ),
              ),
            ],
          ),
        )),
      ],
    );
  }
}
